apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  BETTER_AUTH_SECRET: {{ .Values.secrets.betterAuthSecret | b64enc | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | default "" | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | default "" | b64enc | quote }}
  GITHUB_CLIENT_ID: {{ .Values.secrets.githubClientId | default "" | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.githubClientSecret | default "" | b64enc | quote }}
