apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  BACKEND_URL: {{ .Values.config.backendUrl | quote }}
  NOTIFICATION_URL: {{ .Values.config.notificationUrl | quote }}
