apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.env.openaiApiKey | b64enc | quote }}
  CHAINLIT_AUTH_SECRET: {{ .Values.env.chainlitAuthSecret | b64enc | quote }}
