apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  ALGORITHM: {{ .Values.config.algorithm | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.config.accessTokenExpireMinutes | quote }}
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  DEBUG: {{ .Values.config.debug | quote }}
